### PR TITLE
Snackbar and modal

### PR DESCRIPTION
**Pull request by purvasharmadev**
## Added the modal component.

image

> Updated the links.

### CODE REVIEW

**Review by dev-prabhat — APPROVED** [review]
Naming convention of classes is pretty good, relatable what it is meant and color combination pretty good

**Review by adityapandadev — APPROVED** [review]
Changes Looks Good 👍

**Comment by rishabh486** [comment]
appreciation : clean ui and good code structure 
good to merge

**Review by rishabh486 — APPROVED** [review]
appreciation:good code structure
 good to merge

**Pull request merged**
